spring.application.name=1-Spring-Boot-Application

#spring.main.banner-mode=off
#spring.main.banner-mode=console -> It's by-Default

# ASCII Generator -> https://r.search.yahoo.com/_ylt=Awrx_YgnetBpMwIA_9K7HAx.;_ylu=Y29sbwNzZzMEcG9zAzEEdnRpZAMEc2VjA3Ny/RV=2/RE=1776480040/RO=10/RU=https%3a%2f%2fpatorjk.com%2fsoftware%2ftaag%2f/RK=2/RS=wWAj68MNfJhJdvwY6lCVE9qlzJ4-
