spring:
  application:
    name: 6-Data_JPA_Composite_PK
    
    
    # configure Datasource Property
  datasource:
   url: jdbc:mysql://localhost:3306/sbms27dipu
   username: root
   password: Dipu@123
   driver-class-name: com.mysql.cj.jdbc.Driver 
   
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true  
